threads_by_job: 2
container: gbs_workflow.sif
fastqFolder: /media/superdisk/reservebenefit/donnees/mackerel
runs: 
  - runA
  - runB
  - ...
fastp:
  n_base_limit: 0
  qualified_quality_phred: 18
  unqualified_percent_limit: 40
  length_required: 76
  cut_tail_window_size: 4
  cut_tail_mean_quality: 18
  poly_g_min_len: 10

process_radtags:
    enzyme : SbfI
    trim_length : 142
    score_limit : 20
    sliding_windows_size : 0.20
    encoded : phred33
    barcode_dist_1 : 1
    barcode_dist_2 : 1
    adapter_mm : 2
    adapter_1 : ACACTCTTTCCCTACACGACGCTCTTCCGATCT,AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT,GATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCAGAACAA,CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCC
    adapter_2 : ACACTCTTTCCCTACACGACGCTCTTCCGATCT,AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT,GATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCAGAACAA,CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCC
